SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS zavodnik_boulder_uspesnost_lezecky;
DROP TABLE IF EXISTS boulder;
DROP TABLE IF EXISTS zavodnik;
DROP TABLE IF EXISTS zavod;
DROP TABLE IF EXISTS lezecky;
DROP TABLE IF EXISTS uspesnost;

SET FOREIGN_KEY_CHECKS = 1;
